%YAML 1.2
---
root: true
env:
  browser: true
  node: true
  commonjs: true
  es2022: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  strict:
    - error
    - global
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  no-var: error
  one-var:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  comma-dangle:
    - error
    - never
  eqeqeq:
    - error
    - always
  no-multi-spaces: error
  no-trailing-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
  object-curly-newline:
    - error
    - ObjectPattern:
        minProperties: 1
